# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/life_of_py',
                'doc_host': 'https://maddytae.github.io',
                'git_url': 'https://github.com/maddytae/life_of_py',
                'lib_path': 'life_of_py'},
  'syms': {'life_of_py.core': {'life_of_py.core.foo': ('core.html#foo', 'life_of_py/core.py')}}}